remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have onetitle: Sword Selection
title: Sword Selection
description: An all-new Minecraft Forge mod that adds in a variety of swords to the game.
show_downloads: true
