
modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/SneK152/SwordSelection/issues" #optional

logoFile="swordselection.png" #optional
[[mods]] #mandatory

modId="swordselection" #mandatory
version="0.2.0" #mandatory
displayName="Sword Selection" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="SneK152" #optional
description='''
This mod allows you to have multiple variations and selections of swords. It adds in a variety of swords, knives, and daggers. WIP.
'''
[[dependencies.swordselection]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[36,)" #mandatory
   ordering="NONE"
   side="BOTH"
[[dependencies.swordselection]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
